version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
    reviewers:
      - "tsinis"
    ignore:
      - dependency-name: "*bloc*"
      - dependency-name: "msix"
