version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Flutter
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "*bloc*"
      - dependency-name: "msix"
