version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    commit_message:
      prefix: "chore"
      include_scope: true
    ignore:
      - dependency-name: "*bloc*"
      - dependency-name: "msix"
