version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maintain dependencies for Flutter
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      - dependency-name: "msix"

  # Maintain dependencies for Android
  - package-ecosystem: gradle
    directory: "/android"
    schedule:
      interval: "weekly"
    reviewers:
      - "tsinis"
    commit-message:
      prefix: "chore"
      include: "scope"