include: package:lints/recommended.yaml

analyzer:
  exclude:
    # Web
    - 'web/**'
    # Build
    - 'build/**'
    # Generated code
    - 'lib/**/*.g.dart'
    - 'lib/generated_plugin_registrant.dart'
    - 'lib/generated/**'
    # Assets
    - 'assets/**'
    # Mocks for test
    - 'test/data/**'
    # Conditional imports
    - 'lib/share/repository/conditional_import/**'

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Info
    always_declare_return_types: info
    directives_ordering: info
    todo: info
    unsafe_html: info

    # Warning
    prefer_relative_imports: warning
    no_logic_in_create_state: warning
    empty_catches: warning

    # Error
    always_require_non_null_named_parameters: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    valid_regexps: error

  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 60
  metrics-exclude:
    - test/**
  rules:
    - avoid-nested-conditional-expressions:
      acceptable-level: 2
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - prefer-match-file-name
    - avoid-missing-enum-constant-in-map
    - prefer-correct-type-name
    - prefer-last
    - refer-correct-identifier-length
    - prefer-first
    - prefer-const-border-radius
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-single-widget-per-file
    - prefer-intl-name
    - provide-correct-intl-args
    - member-ordering-extended
    - technical-debt

linter:
  rules:
    # Disabled
    always_specify_types: false
    avoid_annotating_with_dynamic: false
    avoid_as: false # depricated
    avoid_types_on_closure_parameters: false
    comment_references: false
    depend_on_referenced_packages: false # false positive on l10n
    diagnostic_describe_all_properties: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    prefer_double_quotes: false
    prefer_final_parameters: false
    public_member_api_docs: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    unsafe_html: false
    use_key_in_widget_constructors: false

    # Enabled
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    avoid_web_libraries_in_flutter: true
    await_only_futures: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    only_throw_errors: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
    use_raw_strings: true
    use_string_buffers: true
    unnecessary_await_in_return: true
    valid_regexps: true
    void_checks: true

    # Pedantic 1.9.0
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    camel_case_extensions: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true

    # Effective_dart 1.2.0
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    directives_ordering: true
    package_api_docs: true
    implementation_imports: true
    prefer_relative_imports: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_brace_in_string_interps: true
    avoid_function_literals_in_foreach_calls: true
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true
    unnecessary_getters_setters: true
    prefer_initializing_formals: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    use_to_and_as_if_applicable: true
    one_member_abstracts: true
    prefer_mixin: true
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    avoid_returning_null: true
    avoid_returning_this: true
    type_annotate_public_apis: true
    avoid_private_typedef_functions: true
    avoid_positional_boolean_parameters: true
    hash_and_equals: true
    avoid_equals_and_hash_code_on_mutable_classes: true

    # Linter 1.11.0
    exhaustive_cases: true
    unnecessary_constructor_name: true
    eol_at_end_of_file: true
    use_test_throws_matchers: true
    noop_primitive_operations: true
    require_trailing_commas: true
    prefer_null_aware_method_calls: true
    use_build_context_synchronously: true
    avoid_multiple_declarations_per_line: true
    use_if_null_to_convert_nulls_to_bools: true
    deprecated_consistency: true
    use_named_constants: true
    avoid_dynamic_calls: true
    cast_nullable_to_non_nullable: true
    null_check_on_nullable_type_parameter: true
    tighten_type_of_initializing_formals: true
    unnecessary_null_checks: true
    avoid_type_to_string: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_late: true
    do_not_use_environment: true
    no_default_cases: true
    use_is_even_rather_than_modulo: true

    # Linter 1.15.0
    use_decorated_box: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    secure_pubspec_urls: true
    sized_box_shrink_expand: true
    avoid_final_parameters: true