version: 2.0.1+10
name: colors_ai
description: Color scheme generator that uses deep learning from public providers.
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues
maintainer: Roman Cinis

publish_to: 'none'

environment:
  sdk: ">=2.15.0"
  flutter: ">=2.8.1"

dependencies:
  animations: ^2.0.2 # From Google
  color_converter: ^0.2.1
  dart_vlc: 0.1.7 # without experimental iOS implementation
  equatable: ^2.0.3 # From Flutter Community
  file_selector: ^0.8.2+1 # From Google
  file_selector_linux: ^0.0.2+1 # From Google
  file_selector_windows: ^0.0.2+1 # From Google
  flutter:  # From Google
    sdk: flutter
  flutter_bloc: 7.0.0 # Flutter Favorite
  flutter_colorpicker: ^1.0.3 # Contributor
  flutter_localizations: # From Google
     sdk: flutter
  flutter_secure_storage: ^5.0.2
  google_fonts: ^2.2.0 # From Google
  http: ^0.13.0-nullsafety.0 # From Google
  hydrated_bloc: 7.0.1
  intl: ^0.17.0 # From Google
  json_annotation: ^4.4.0 # From Google
  just_audio: ^0.9.18 # Flutter Favorite
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^1.3.0 # From Flutter Community (former Google)
  path_provider: ^2.0.8 # From Google
  platform_info: ^3.1.0 # Contributor
  printing: ^5.6.6
  share_plus: ^3.0.4 # From Flutter Community (former Google)
  simple_animations: ^4.0.1
  url_launcher: ^6.0.0-nullsafety.7 # From Google
  vibration: ^1.7.4-nullsafety.0
  window_size: # From Google
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: c339fe7dd2e17a80f7bb839bfad89d21a6e084ba

dev_dependencies:
  bloc_test: 8.5.0
  build_runner: ^2.1.7 # From Google
  dart_code_metrics: ^4.8.1 # Flutter Favorite
  flutter_lints: ^1.0.4  # From Google
  flutter_test: # From Google
    sdk: flutter
  golden_toolkit: ^0.12.0
  hive_generator: ^1.1.1
  integration_test: # From Google
    sdk: flutter
  json_serializable: ^6.1.3 # From Google
  mockito: ^5.0.0-nullsafety.5 # From Google
  msix: ^2.8.0 # Recommended by Google

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/sounds/

msix_config:
  architecture: x64
  capabilities: "internetClient"
  display_name: Colors AI
  identity_name: 53621RomanCinis.ColorsAI
  languages: en-us, sk-sk, ru-ru, cs-cz
  logo_path: snap\gui\colors-ai-icon.svg
  msix_version: 2.0.1.0
  publisher_display_name: Roman Cinis
  publisher: CN=3F745294-7EE6-4235-B7C5-8E22B9089351
  store: true