name: colors_ai
description: Color scheme generator that uses deep learning from Colormind API.
author: Roman Cinis
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues

publish_to: 'none'

version: 1.1.0+3

environment:
  sdk: ">=2.14.0-129.0.dev <3.0.0" # with NavigationBar from Material You
  # git clone -b feature-navigationBar https://github.com/johnsonmh/flutter.git
  flutter: ">=2.3.0-13.0.pre.63 <3.0.0"

dependencies:
  color_converter: ^0.2.1
  equatable: ^2.0.3 # From Flutter Community
  flutter:  # From Google
    sdk: flutter
  flutter_bloc: ^7.0.0 # Flutter Favorite
  flutter_colorpicker: ^0.5.0 # Contributor
  flutter_localizations: # From Google
     sdk: flutter
  http: ^0.13.0-nullsafety.0 # From Google
  hydrated_bloc: ^7.0.1
  intl: ^0.17.0 # From Google
  json_annotation: ^4.0.0-nullsafety.0 # From Google
  just_audio: ^0.8.0 # Flutter Favorite
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^1.0.4 # From Flutter Community
  path_provider: ^2.0.2 # From Google
  printing: ^5.4.3
  share_plus: ^2.1.4 # From Flutter Community
  simple_animations: ^3.0.0-nullsafety.4
  url_launcher: ^6.0.0-nullsafety.7 # From Google
  vibration: ^1.7.4-nullsafety.0

dev_dependencies:
  build_runner: ^2.0.6 # From Google
  # flutter_native_splash: ^0.2.11
  flutter_test: # From Google
    sdk: flutter
  hive_generator: ^1.1.0
  integration_test: # From Google
    sdk: flutter
  json_serializable: ^4.1.4-nullsafety.0 # From Google
  mockito: ^5.0.0-nullsafety.5 # From Google
  pedantic: ^1.10.0-nullsafety.3 # From Google

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/
