name: colors_ai
description: Color scheme generator that uses deep learning from Colormind API.
author: Roman Cinis
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.13.0-116.0.dev <3.0.0"
  flutter: ">=2.1.0-12.2.pre <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_colorpicker: ^0.4.0-nullsafety.0
  hive: ^2.0.3
  hive_flutter: ^1.0.0-nullsafety.0
  http: ^0.13.0-nullsafety.0
  json_annotation: ^4.0.0-nullsafety.0
  just_audio: ^0.7.0-nullsafety.1
  mdi: ^5.0.0-nullsafety.0
  package_info: ^2.0.0
  share: ^2.0.0-nullsafety.2
  simple_animations: ^3.0.0-nullsafety.4
  url_launcher: ^6.0.0-nullsafety.7
  vibration: ^1.7.4-nullsafety.0


dev_dependencies:
  build_runner:
  # json_serializable: ^4.0.0-nullsafety.0
  # flutter_driver:
  #   sdk: flutter
  # flutter_native_splash: ^0.2.9
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  integration_test:
    sdk: flutter
  # mockito: ^5.0.0-nullsafety.5
  pedantic: ^1.10.0-nullsafety.3

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/app_icon.png
