version: 2.2.2+14
name: colors_ai
description: Color scheme generator that uses deep learning from public providers.
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues
maintainer: Roman Cinis

publish_to: "none"

environment:
  sdk: ^3.3.0

dependencies:
  animations: ^2.0.11 # From Google
  audioplayers: ^5.2.1
  color_converter: ^0.2.1
  equatable: ^2.0.5 # From Flutter Community
  file_selector: ^1.0.3 # From Google
  flutter: # From Google
    sdk: flutter
  flutter_bloc: ^8.1.5  # Flutter Favorite, Contributor
  flutter_colorpicker: ^1.0.3 # Contributor
  flutter_localizations: # From Google
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1 # for Freezed
  google_fonts: ^6.2.1 # From Google
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0 # From Google
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^8.0.0 # From Flutter Community (former Google)
  path_provider: ^2.1.3 # From Google
  platform_info: ^4.0.2 # Contributor
  printing: ^5.12.0
  share_plus: ^9.0.0 # From Flutter Community (former Google)
  simple_animations: ^5.0.2
  stream_bloc: ^0.5.3
  url_launcher: ^6.2.6 # From Google
  vibration: 1.7.7
  window_size: # From Google
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.9 # From Google
  dart_code_metrics: # Flutter Favorite
    git:
      url: https://github.com/tsinis/dart-code-metrics
    version: 5.8.0+1
  flutter_lints: ^3.0.2 # From Google
  flutter_test: # From Google
    sdk: flutter
  freezed: ^2.5.2 # Flutter Favorite
  hive_generator: ^2.0.1
  integration_test: # From Google
    sdk: flutter
  json_serializable: ^6.8.0 # From Google
  mockito: ^5.4.4 # From Google
  msix: 2.7.3 # Flutter Favorite (generating from SVG)

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/sounds/

msix_config:
  architecture: x64
  capabilities: "internetClient"
  display_name: Colors AI
  identity_name: 53621RomanCinis.ColorsAI
  languages: en-us, sk-sk, ru-ru, cs-cz
  logo_path: snap\gui\colors-ai-icon.svg
  msix_version: 2.2.2.0
  publisher_display_name: Roman Cinis
  publisher: CN=3F745294-7EE6-4235-B7C5-8E22B9089351
  store: true

spider:
  generate_tests: true
  no_comments: true
  export: false
  groups:
    - path: assets/google_fonts
      class_name: Fonts
      types: [.ttf]
    - path: assets/sounds
      class_name: Sounds
      types: [.mp3]
