name: colors_ai
description: Color scheme generator that uses deep learning from Colormind API.
author: Roman Cinis
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.12.0-133.7.beta <3.0.0"
  flutter: ">=1.23.0-14.0.pre <2.0.0"

dependencies:
  equatable: ^2.0.0-nullsafety.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0-nullsafety.1
  flutter_colorpicker: ^0.4.0-nullsafety.0
  hive: ^1.6.0-nullsafety.1
  hive_flutter:
  http: ^0.13.0-nullsafety.0
  json_annotation: ^4.0.0-nullsafety.0
  just_audio: ^0.6.9
  mdi: ^5.0.0-nullsafety.0
  share: ^2.0.0-nullsafety.2
  simple_animations: ^3.0.0-nullsafety.3
  url_launcher: ^6.0.0-nullsafety.6
  vibration: ^1.7.4-nullsafety.0

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0

dev_dependencies:
  # build_runner:
  # json_serializable: ^4.0.0-nullsafety.0
  # hive_generator: ^0.9.0-nullsafety.0
  # flutter_driver:
  #   sdk: flutter

  # flutter_native_splash: ^0.2.9
  flutter_test:
    sdk: flutter
  # integration_test:
  #   sdk: flutter
  integration_test: ^1.0.2+2
  # mockito: ^5.0.0-nullsafety.5
  pedantic: ^1.10.0-nullsafety.3

# integration_test:
#   sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/app_icon.png
