version: 2.2.1+13
name: colors_ai
description: Color scheme generator that uses deep learning from public providers.
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues
maintainer: Roman Cinis

publish_to: "none"

environment:
  sdk: ">=2.18.0"
  flutter: ">=3.3.4"

dependencies:
  animations: ^2.0.7 # From Google
  audioplayers: ^1.1.1
  color_converter: ^0.2.1
  equatable: ^2.0.5 # From Flutter Community
  file_selector: ^0.9.2+2 # From Google
  flutter: # From Google
    sdk: flutter
  flutter_bloc: ^8.1.1  # Flutter Favorite
  flutter_colorpicker: ^1.0.3 # Contributor
  flutter_localizations: # From Google
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.2.0 # for Freezed
  google_fonts: ^3.0.1 # From Google
  http: ^0.13.5 # From Google
  hydrated_bloc: 9.0.0
  intl: ^0.17.0 # From Google
  json_annotation: ^4.7.0 # From Google
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^3.0.2 # From Flutter Community (former Google)
  path_provider: ^2.0.11 # From Google
  platform_info: ^3.2.0 # Contributor
  printing: ^5.9.3
  share_plus: ^6.3.0 # From Flutter Community (former Google)
  simple_animations: ^5.0.0+2
  stream_bloc: ^0.5.3
  url_launcher: ^6.1.6 # From Google
  vibration: ^1.7.6
  window_size: # From Google
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  bloc_test: 9.1.0
  build_runner: ^2.3.2 # From Google
  code_builder: ^4.3.0 # From Google
  dart_code_metrics: ^5.0.1 # Flutter Favorite
  flutter_lints: ^2.0.1 # From Google
  flutter_test: # From Google
    sdk: flutter
  freezed: ^2.2.1 # Flutter Favorite
  golden_toolkit: ^0.13.0
  hive_generator: ^2.0.0
  integration_test: # From Google
    sdk: flutter
  json_serializable: ^6.5.4 # From Google
  linter: ^1.30.0 # From Google
  mockito: ^5.3.2 # From Google
  msix: 2.7.3 # Flutter Favorite (generating from SVG)

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/sounds/

msix_config:
  architecture: x64
  capabilities: "internetClient"
  display_name: Colors AI
  identity_name: 53621RomanCinis.ColorsAI
  languages: en-us, sk-sk, ru-ru, cs-cz
  logo_path: snap\gui\colors-ai-icon.svg
  msix_version: 2.2.1.0
  publisher_display_name: Roman Cinis
  publisher: CN=3F745294-7EE6-4235-B7C5-8E22B9089351
  store: true

spider:
  generate_tests: true
  no_comments: true
  export: false
  groups:
    - path: assets/google_fonts
      class_name: Fonts
      types: [.ttf]
    - path: assets/sounds
      class_name: Sounds
      types: [.mp3]
