version: 2.0.1+10
name: colors_ai
description: Color scheme generator that uses deep learning from public providers.
repository: https://github.com/tsinis/colors_ai
issue_tracker: https://github.com/tsinis/colors_ai/issues
maintainer: Roman Cinis

publish_to: 'none'

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.0"

dependencies:
  animations: ^2.0.3 # From Google
  audioplayers: ^1.0.0-rc.4
  color_converter: ^0.2.1
  equatable: ^2.0.3 # From Flutter Community
  file_selector: 0.8.4+2 # From Google
  file_selector_linux: ^0.0.2+1 # From Google
  file_selector_windows: ^0.8.2+1 # From Google
  flutter:  # From Google
    sdk: flutter
  flutter_bloc: 7.0.0 # Flutter Favorite
  flutter_colorpicker: ^1.0.3 # Contributor
  flutter_localizations: # From Google
     sdk: flutter
  flutter_secure_storage: ^5.0.2
  google_fonts: ^3.0.1 # From Google
  http: ^0.13.0-nullsafety.0 # From Google
  hydrated_bloc: 7.0.1
  intl: ^0.17.0 # From Google
  json_annotation: ^4.5.0 # From Google
  mdi: ^5.0.0-nullsafety.0
  package_info_plus: ^1.4.2 # From Flutter Community (former Google)
  path_provider: ^2.0.10 # From Google
  platform_info: ^3.2.0 # Contributor
  printing: ^5.9.1
  share_plus: ^4.0.4 # From Flutter Community (former Google)
  simple_animations: ^4.0.2
  url_launcher: ^6.0.0-nullsafety.7 # From Google
  vibration: ^1.7.4-nullsafety.0
  window_size: # From Google
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: 5c51870ced62a00e809ba4b81a846a052d241c9f

dev_dependencies:
  bloc_test: 8.5.0
  build_runner: ^2.1.11 # From Google
  dart_code_metrics: ^4.15.2 # Flutter Favorite
  flutter_lints: ^2.0.1  # From Google
  flutter_test: # From Google
    sdk: flutter
  golden_toolkit: ^0.13.0
  hive_generator: ^1.1.3
  integration_test: # From Google
    sdk: flutter
  json_serializable: ^6.2.0 # From Google
  mockito: ^5.0.0-nullsafety.5 # From Google
  msix: 2.7.3 # Recommended by Google (generating from SVG)

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/sounds/

msix_config:
  architecture: x64
  capabilities: "internetClient"
  display_name: Colors AI
  identity_name: 53621RomanCinis.ColorsAI
  languages: en-us, sk-sk, ru-ru, cs-cz
  logo_path: snap\gui\colors-ai-icon.svg
  msix_version: 2.0.1.0
  publisher_display_name: Roman Cinis
  publisher: CN=3F745294-7EE6-4235-B7C5-8E22B9089351
  store: true