// Mocks generated by Mockito 5.0.17 from annotations
// in colors_ai/test/data/mocks/generated.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;
import 'dart:ui' as _i4;

import 'package:colors_ai/core/services/url_launcher.dart' as _i7;
import 'package:colors_ai/sound/services/sounds_player.dart' as _i6;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:window_size/src/platform_window.dart' as _i3;
import 'package:window_size/src/screen.dart' as _i9;
import 'package:window_size/src/window_size_channel.dart' as _i8;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeIOSOptions_0 extends _i1.Fake implements _i2.IOSOptions {}

class _FakeAndroidOptions_1 extends _i1.Fake implements _i2.AndroidOptions {}

class _FakeLinuxOptions_2 extends _i1.Fake implements _i2.LinuxOptions {}

class _FakeWindowsOptions_3 extends _i1.Fake implements _i2.WindowsOptions {}

class _FakeWebOptions_4 extends _i1.Fake implements _i2.WebOptions {}

class _FakeMacOsOptions_5 extends _i1.Fake implements _i2.MacOsOptions {}

class _FakePlatformWindow_6 extends _i1.Fake implements _i3.PlatformWindow {}

class _FakeSize_7 extends _i1.Fake implements _i4.Size {}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i2.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IOSOptions get iOptions =>
      (super.noSuchMethod(Invocation.getter(#iOptions),
          returnValue: _FakeIOSOptions_0()) as _i2.IOSOptions);
  @override
  _i2.AndroidOptions get aOptions =>
      (super.noSuchMethod(Invocation.getter(#aOptions),
          returnValue: _FakeAndroidOptions_1()) as _i2.AndroidOptions);
  @override
  _i2.LinuxOptions get lOptions =>
      (super.noSuchMethod(Invocation.getter(#lOptions),
          returnValue: _FakeLinuxOptions_2()) as _i2.LinuxOptions);
  @override
  _i2.WindowsOptions get wOptions =>
      (super.noSuchMethod(Invocation.getter(#wOptions),
          returnValue: _FakeWindowsOptions_3()) as _i2.WindowsOptions);
  @override
  _i2.WebOptions get webOptions =>
      (super.noSuchMethod(Invocation.getter(#webOptions),
          returnValue: _FakeWebOptions_4()) as _i2.WebOptions);
  @override
  _i2.MacOsOptions get mOptions =>
      (super.noSuchMethod(Invocation.getter(#mOptions),
          returnValue: _FakeMacOsOptions_5()) as _i2.MacOsOptions);
  @override
  _i5.Future<void> write(
          {String? key,
          String? value,
          _i2.IOSOptions? iOptions,
          _i2.AndroidOptions? aOptions,
          _i2.LinuxOptions? lOptions,
          _i2.WebOptions? webOptions,
          _i2.MacOsOptions? mOptions,
          _i2.WindowsOptions? wOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#write, [], {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<String?> read(
          {String? key,
          _i2.IOSOptions? iOptions,
          _i2.AndroidOptions? aOptions,
          _i2.LinuxOptions? lOptions,
          _i2.WebOptions? webOptions,
          _i2.MacOsOptions? mOptions,
          _i2.WindowsOptions? wOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#read, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions
          }),
          returnValue: Future<String?>.value()) as _i5.Future<String?>);
  @override
  _i5.Future<bool> containsKey(
          {String? key,
          _i2.IOSOptions? iOptions,
          _i2.AndroidOptions? aOptions,
          _i2.LinuxOptions? lOptions,
          _i2.WebOptions? webOptions,
          _i2.MacOsOptions? mOptions,
          _i2.WindowsOptions? wOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#containsKey, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions
          }),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  _i5.Future<void> delete(
          {String? key,
          _i2.IOSOptions? iOptions,
          _i2.AndroidOptions? aOptions,
          _i2.LinuxOptions? lOptions,
          _i2.WebOptions? webOptions,
          _i2.MacOsOptions? mOptions,
          _i2.WindowsOptions? wOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#delete, [], {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<Map<String, String>> readAll(
          {_i2.IOSOptions? iOptions,
          _i2.AndroidOptions? aOptions,
          _i2.LinuxOptions? lOptions,
          _i2.WebOptions? webOptions,
          _i2.MacOsOptions? mOptions,
          _i2.WindowsOptions? wOptions}) =>
      (super.noSuchMethod(
              Invocation.method(#readAll, [], {
                #iOptions: iOptions,
                #aOptions: aOptions,
                #lOptions: lOptions,
                #webOptions: webOptions,
                #mOptions: mOptions,
                #wOptions: wOptions
              }),
              returnValue:
                  Future<Map<String, String>>.value(<String, String>{}))
          as _i5.Future<Map<String, String>>);
  @override
  _i5.Future<void> deleteAll(
          {_i2.IOSOptions? iOptions,
          _i2.AndroidOptions? aOptions,
          _i2.LinuxOptions? lOptions,
          _i2.WebOptions? webOptions,
          _i2.MacOsOptions? mOptions,
          _i2.WindowsOptions? wOptions}) =>
      (super.noSuchMethod(
          Invocation.method(#deleteAll, [], {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
}

/// A class which mocks [SoundsPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoundsPlayer extends _i1.Mock implements _i6.SoundsPlayer {
  MockSoundsPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> playSound(String? asset, double? volume,
          {bool? cacheOnly = false}) =>
      (super.noSuchMethod(
          Invocation.method(
              #playSound, [asset, volume], {#cacheOnly: cacheOnly}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
}

/// A class which mocks [UrlLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLauncher extends _i1.Mock implements _i7.UrlLauncher {
  MockUrlLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> openURL([String? url]) =>
      (super.noSuchMethod(Invocation.method(#openURL, [url]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}

/// A class which mocks [WindowSizeChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWindowSizeChannel extends _i1.Mock implements _i8.WindowSizeChannel {
  MockWindowSizeChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i9.Screen>> getScreenList() =>
      (super.noSuchMethod(Invocation.method(#getScreenList, []),
              returnValue: Future<List<_i9.Screen>>.value(<_i9.Screen>[]))
          as _i5.Future<List<_i9.Screen>>);
  @override
  _i5.Future<_i3.PlatformWindow> getWindowInfo() =>
      (super.noSuchMethod(Invocation.method(#getWindowInfo, []),
              returnValue:
                  Future<_i3.PlatformWindow>.value(_FakePlatformWindow_6()))
          as _i5.Future<_i3.PlatformWindow>);
  @override
  void setWindowFrame(_i4.Rect? frame) =>
      super.noSuchMethod(Invocation.method(#setWindowFrame, [frame]),
          returnValueForMissingStub: null);
  @override
  void setWindowMinSize(_i4.Size? size) =>
      super.noSuchMethod(Invocation.method(#setWindowMinSize, [size]),
          returnValueForMissingStub: null);
  @override
  void setWindowVisibility({bool? visible}) => super.noSuchMethod(
      Invocation.method(#setWindowVisibility, [], {#visible: visible}),
      returnValueForMissingStub: null);
  @override
  void setWindowMaxSize(_i4.Size? size) =>
      super.noSuchMethod(Invocation.method(#setWindowMaxSize, [size]),
          returnValueForMissingStub: null);
  @override
  void setWindowTitle(String? title) =>
      super.noSuchMethod(Invocation.method(#setWindowTitle, [title]),
          returnValueForMissingStub: null);
  @override
  void setWindowTitleRepresentedUrl(Uri? file) => super.noSuchMethod(
      Invocation.method(#setWindowTitleRepresentedUrl, [file]),
      returnValueForMissingStub: null);
  @override
  _i5.Future<_i4.Size> getWindowMinSize() =>
      (super.noSuchMethod(Invocation.method(#getWindowMinSize, []),
              returnValue: Future<_i4.Size>.value(_FakeSize_7()))
          as _i5.Future<_i4.Size>);
  @override
  _i5.Future<_i4.Size> getWindowMaxSize() =>
      (super.noSuchMethod(Invocation.method(#getWindowMaxSize, []),
              returnValue: Future<_i4.Size>.value(_FakeSize_7()))
          as _i5.Future<_i4.Size>);
}
