// Mocks generated by Mockito 5.4.2 from annotations
// in colors_ai/test/data/mocks/generated.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:convert' as _i10;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i8;

import 'package:audioplayers/audioplayers.dart' as _i2;
import 'package:colors_ai/core/services/url_launcher.dart' as _i12;
import 'package:colors_ai/sound/services/sounds_player.dart' as _i11;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:hive/hive.dart' as _i5;
import 'package:hive/src/object/hive_object.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:window_size/src/platform_window.dart' as _i7;
import 'package:window_size/src/screen.dart' as _i14;
import 'package:window_size/src/window_size_channel.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAudioCache_0 extends _i1.SmartFake implements _i2.AudioCache {
  _FakeAudioCache_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCompleter_1<T> extends _i1.SmartFake implements _i3.Completer<T> {
  _FakeCompleter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHiveList_2<E extends _i4.HiveObjectMixin> extends _i1.SmartFake
    implements _i5.HiveList<E> {
  _FakeHiveList_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_3 extends _i1.SmartFake implements _i6.IOSOptions {
  _FakeIOSOptions_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_4 extends _i1.SmartFake
    implements _i6.AndroidOptions {
  _FakeAndroidOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_5 extends _i1.SmartFake implements _i6.LinuxOptions {
  _FakeLinuxOptions_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_6 extends _i1.SmartFake
    implements _i6.WindowsOptions {
  _FakeWindowsOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_7 extends _i1.SmartFake implements _i6.WebOptions {
  _FakeWebOptions_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMacOsOptions_8 extends _i1.SmartFake implements _i6.MacOsOptions {
  _FakeMacOsOptions_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlatformWindow_9 extends _i1.SmartFake
    implements _i7.PlatformWindow {
  _FakePlatformWindow_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSize_10 extends _i1.SmartFake implements _i8.Size {
  _FakeSize_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i2.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AudioCache get audioCache => (super.noSuchMethod(
        Invocation.getter(#audioCache),
        returnValue: _FakeAudioCache_0(
          this,
          Invocation.getter(#audioCache),
        ),
      ) as _i2.AudioCache);
  @override
  set audioCache(_i2.AudioCache? _audioCache) => super.noSuchMethod(
        Invocation.setter(
          #audioCache,
          _audioCache,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get playerId => (super.noSuchMethod(
        Invocation.getter(#playerId),
        returnValue: '',
      ) as String);
  @override
  _i3.Completer<void> get creatingCompleter => (super.noSuchMethod(
        Invocation.getter(#creatingCompleter),
        returnValue: _FakeCompleter_1<void>(
          this,
          Invocation.getter(#creatingCompleter),
        ),
      ) as _i3.Completer<void>);
  @override
  double get volume => (super.noSuchMethod(
        Invocation.getter(#volume),
        returnValue: 0.0,
      ) as double);
  @override
  double get balance => (super.noSuchMethod(
        Invocation.getter(#balance),
        returnValue: 0.0,
      ) as double);
  @override
  double get playbackRate => (super.noSuchMethod(
        Invocation.getter(#playbackRate),
        returnValue: 0.0,
      ) as double);
  @override
  _i2.PlayerMode get mode => (super.noSuchMethod(
        Invocation.getter(#mode),
        returnValue: _i2.PlayerMode.mediaPlayer,
      ) as _i2.PlayerMode);
  @override
  _i2.ReleaseMode get releaseMode => (super.noSuchMethod(
        Invocation.getter(#releaseMode),
        returnValue: _i2.ReleaseMode.release,
      ) as _i2.ReleaseMode);
  @override
  _i2.PlayerState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i2.PlayerState.stopped,
      ) as _i2.PlayerState);
  @override
  set state(_i2.PlayerState? state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          state,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Stream<_i2.AudioEvent> get eventStream => (super.noSuchMethod(
        Invocation.getter(#eventStream),
        returnValue: _i3.Stream<_i2.AudioEvent>.empty(),
      ) as _i3.Stream<_i2.AudioEvent>);
  @override
  _i3.Stream<_i2.PlayerState> get onPlayerStateChanged => (super.noSuchMethod(
        Invocation.getter(#onPlayerStateChanged),
        returnValue: _i3.Stream<_i2.PlayerState>.empty(),
      ) as _i3.Stream<_i2.PlayerState>);
  @override
  _i3.Stream<Duration> get onPositionChanged => (super.noSuchMethod(
        Invocation.getter(#onPositionChanged),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);
  @override
  _i3.Stream<Duration> get onDurationChanged => (super.noSuchMethod(
        Invocation.getter(#onDurationChanged),
        returnValue: _i3.Stream<Duration>.empty(),
      ) as _i3.Stream<Duration>);
  @override
  _i3.Stream<void> get onPlayerComplete => (super.noSuchMethod(
        Invocation.getter(#onPlayerComplete),
        returnValue: _i3.Stream<void>.empty(),
      ) as _i3.Stream<void>);
  @override
  _i3.Stream<void> get onSeekComplete => (super.noSuchMethod(
        Invocation.getter(#onSeekComplete),
        returnValue: _i3.Stream<void>.empty(),
      ) as _i3.Stream<void>);
  @override
  _i3.Stream<String> get onLog => (super.noSuchMethod(
        Invocation.getter(#onLog),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);
  @override
  _i3.Future<void> play(
    _i2.Source? source, {
    double? volume,
    double? balance,
    _i2.AudioContext? ctx,
    Duration? position,
    _i2.PlayerMode? mode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #play,
          [source],
          {
            #volume: volume,
            #balance: balance,
            #ctx: ctx,
            #position: position,
            #mode: mode,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setAudioContext(_i2.AudioContext? ctx) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAudioContext,
          [ctx],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setPlayerMode(_i2.PlayerMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setPlayerMode,
          [mode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> release() => (super.noSuchMethod(
        Invocation.method(
          #release,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> seek(Duration? position) => (super.noSuchMethod(
        Invocation.method(
          #seek,
          [position],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setBalance(double? balance) => (super.noSuchMethod(
        Invocation.method(
          #setBalance,
          [balance],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setReleaseMode(_i2.ReleaseMode? releaseMode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setReleaseMode,
          [releaseMode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setPlaybackRate(double? playbackRate) => (super.noSuchMethod(
        Invocation.method(
          #setPlaybackRate,
          [playbackRate],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setSource(_i2.Source? source) => (super.noSuchMethod(
        Invocation.method(
          #setSource,
          [source],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setSourceUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #setSourceUrl,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setSourceDeviceFile(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setSourceDeviceFile,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setSourceAsset(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setSourceAsset,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<void> setSourceBytes(_i9.Uint8List? bytes) => (super.noSuchMethod(
        Invocation.method(
          #setSourceBytes,
          [bytes],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<Duration?> getDuration() => (super.noSuchMethod(
        Invocation.method(
          #getDuration,
          [],
        ),
        returnValue: _i3.Future<Duration?>.value(),
      ) as _i3.Future<Duration?>);
  @override
  _i3.Future<Duration?> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i3.Future<Duration?>.value(),
      ) as _i3.Future<Duration?>);
  @override
  _i3.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [BinaryReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockBinaryReader extends _i1.Mock implements _i5.BinaryReader {
  MockBinaryReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get availableBytes => (super.noSuchMethod(
        Invocation.getter(#availableBytes),
        returnValue: 0,
      ) as int);
  @override
  int get usedBytes => (super.noSuchMethod(
        Invocation.getter(#usedBytes),
        returnValue: 0,
      ) as int);
  @override
  void skip(int? bytes) => super.noSuchMethod(
        Invocation.method(
          #skip,
          [bytes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  int readByte() => (super.noSuchMethod(
        Invocation.method(
          #readByte,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  _i9.Uint8List viewBytes(int? bytes) => (super.noSuchMethod(
        Invocation.method(
          #viewBytes,
          [bytes],
        ),
        returnValue: _i9.Uint8List(0),
      ) as _i9.Uint8List);
  @override
  _i9.Uint8List peekBytes(int? bytes) => (super.noSuchMethod(
        Invocation.method(
          #peekBytes,
          [bytes],
        ),
        returnValue: _i9.Uint8List(0),
      ) as _i9.Uint8List);
  @override
  int readWord() => (super.noSuchMethod(
        Invocation.method(
          #readWord,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  int readInt32() => (super.noSuchMethod(
        Invocation.method(
          #readInt32,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  int readUint32() => (super.noSuchMethod(
        Invocation.method(
          #readUint32,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  int readInt() => (super.noSuchMethod(
        Invocation.method(
          #readInt,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  double readDouble() => (super.noSuchMethod(
        Invocation.method(
          #readDouble,
          [],
        ),
        returnValue: 0.0,
      ) as double);
  @override
  bool readBool() => (super.noSuchMethod(
        Invocation.method(
          #readBool,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  String readString([
    int? byteCount,
    _i10.Converter<List<int>, String>? decoder = const _i10.Utf8Decoder(),
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #readString,
          [
            byteCount,
            decoder,
          ],
        ),
        returnValue: '',
      ) as String);
  @override
  _i9.Uint8List readByteList([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #readByteList,
          [length],
        ),
        returnValue: _i9.Uint8List(0),
      ) as _i9.Uint8List);
  @override
  List<int> readIntList([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #readIntList,
          [length],
        ),
        returnValue: <int>[],
      ) as List<int>);
  @override
  List<double> readDoubleList([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #readDoubleList,
          [length],
        ),
        returnValue: <double>[],
      ) as List<double>);
  @override
  List<bool> readBoolList([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #readBoolList,
          [length],
        ),
        returnValue: <bool>[],
      ) as List<bool>);
  @override
  List<String> readStringList([
    int? length,
    _i10.Converter<List<int>, String>? decoder = const _i10.Utf8Decoder(),
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #readStringList,
          [
            length,
            decoder,
          ],
        ),
        returnValue: <String>[],
      ) as List<String>);
  @override
  List<dynamic> readList([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #readList,
          [length],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);
  @override
  Map<dynamic, dynamic> readMap([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #readMap,
          [length],
        ),
        returnValue: <dynamic, dynamic>{},
      ) as Map<dynamic, dynamic>);
  @override
  _i5.HiveList<_i4.HiveObjectMixin> readHiveList([int? length]) =>
      (super.noSuchMethod(
        Invocation.method(
          #readHiveList,
          [length],
        ),
        returnValue: _FakeHiveList_2<_i4.HiveObjectMixin>(
          this,
          Invocation.method(
            #readHiveList,
            [length],
          ),
        ),
      ) as _i5.HiveList<_i4.HiveObjectMixin>);
}

/// A class which mocks [BinaryWriter].
///
/// See the documentation for Mockito's code generation for more information.
class MockBinaryWriter extends _i1.Mock implements _i5.BinaryWriter {
  MockBinaryWriter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void writeByte(int? byte) => super.noSuchMethod(
        Invocation.method(
          #writeByte,
          [byte],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeWord(int? value) => super.noSuchMethod(
        Invocation.method(
          #writeWord,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeInt32(int? value) => super.noSuchMethod(
        Invocation.method(
          #writeInt32,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeUint32(int? value) => super.noSuchMethod(
        Invocation.method(
          #writeUint32,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeInt(int? value) => super.noSuchMethod(
        Invocation.method(
          #writeInt,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeDouble(double? value) => super.noSuchMethod(
        Invocation.method(
          #writeDouble,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeBool(bool? value) => super.noSuchMethod(
        Invocation.method(
          #writeBool,
          [value],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeString(
    String? value, {
    bool? writeByteCount = true,
    _i10.Converter<String, List<int>>? encoder = const _i10.Utf8Encoder(),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeString,
          [value],
          {
            #writeByteCount: writeByteCount,
            #encoder: encoder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeByteList(
    List<int>? bytes, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeByteList,
          [bytes],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeIntList(
    List<int>? list, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeIntList,
          [list],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeDoubleList(
    List<double>? list, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeDoubleList,
          [list],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeBoolList(
    List<bool>? list, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeBoolList,
          [list],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeStringList(
    List<String>? list, {
    bool? writeLength = true,
    _i10.Converter<String, List<int>>? encoder = const _i10.Utf8Encoder(),
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeStringList,
          [list],
          {
            #writeLength: writeLength,
            #encoder: encoder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeList(
    List<dynamic>? list, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeList,
          [list],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeMap(
    Map<dynamic, dynamic>? map, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeMap,
          [map],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void writeHiveList(
    _i5.HiveList<_i4.HiveObjectMixin>? list, {
    bool? writeLength = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #writeHiveList,
          [list],
          {#writeLength: writeLength},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void write<T>(
    T? value, {
    bool? writeTypeId = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #write,
          [value],
          {#writeTypeId: writeTypeId},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i6.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_3(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i6.IOSOptions);
  @override
  _i6.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_4(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i6.AndroidOptions);
  @override
  _i6.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_5(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i6.LinuxOptions);
  @override
  _i6.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_6(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i6.WindowsOptions);
  @override
  _i6.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_7(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i6.WebOptions);
  @override
  _i6.MacOsOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeMacOsOptions_8(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i6.MacOsOptions);
  @override
  _i3.Future<void> write({
    required String? key,
    required String? value,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<String?> read({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);
  @override
  _i3.Future<bool> containsKey({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> delete({
    required String? key,
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
  @override
  _i3.Future<Map<String, String>> readAll({
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i3.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i3.Future<Map<String, String>>);
  @override
  _i3.Future<void> deleteAll({
    _i6.IOSOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.MacOsOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [SoundsPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockSoundsPlayer extends _i1.Mock implements _i11.SoundsPlayer {
  MockSoundsPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> playSound(
    String? asset,
    double? volume, {
    List<String>? cachedFileNames,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #playSound,
          [
            asset,
            volume,
          ],
          {#cachedFileNames: cachedFileNames},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [UrlLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockUrlLauncher extends _i1.Mock implements _i12.UrlLauncher {
  MockUrlLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> openURL(String? url) => (super.noSuchMethod(
        Invocation.method(
          #openURL,
          [url],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [WindowSizeChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWindowSizeChannel extends _i1.Mock implements _i13.WindowSizeChannel {
  MockWindowSizeChannel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i14.Screen>> getScreenList() => (super.noSuchMethod(
        Invocation.method(
          #getScreenList,
          [],
        ),
        returnValue: _i3.Future<List<_i14.Screen>>.value(<_i14.Screen>[]),
      ) as _i3.Future<List<_i14.Screen>>);
  @override
  _i3.Future<_i7.PlatformWindow> getWindowInfo() => (super.noSuchMethod(
        Invocation.method(
          #getWindowInfo,
          [],
        ),
        returnValue: _i3.Future<_i7.PlatformWindow>.value(_FakePlatformWindow_9(
          this,
          Invocation.method(
            #getWindowInfo,
            [],
          ),
        )),
      ) as _i3.Future<_i7.PlatformWindow>);
  @override
  void setWindowFrame(_i8.Rect? frame) => super.noSuchMethod(
        Invocation.method(
          #setWindowFrame,
          [frame],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setWindowMinSize(_i8.Size? size) => super.noSuchMethod(
        Invocation.method(
          #setWindowMinSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setWindowVisibility({required bool? visible}) => super.noSuchMethod(
        Invocation.method(
          #setWindowVisibility,
          [],
          {#visible: visible},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setWindowMaxSize(_i8.Size? size) => super.noSuchMethod(
        Invocation.method(
          #setWindowMaxSize,
          [size],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setWindowTitle(String? title) => super.noSuchMethod(
        Invocation.method(
          #setWindowTitle,
          [title],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void setWindowTitleRepresentedUrl(Uri? file) => super.noSuchMethod(
        Invocation.method(
          #setWindowTitleRepresentedUrl,
          [file],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Future<_i8.Size> getWindowMinSize() => (super.noSuchMethod(
        Invocation.method(
          #getWindowMinSize,
          [],
        ),
        returnValue: _i3.Future<_i8.Size>.value(_FakeSize_10(
          this,
          Invocation.method(
            #getWindowMinSize,
            [],
          ),
        )),
      ) as _i3.Future<_i8.Size>);
  @override
  _i3.Future<_i8.Size> getWindowMaxSize() => (super.noSuchMethod(
        Invocation.method(
          #getWindowMaxSize,
          [],
        ),
        returnValue: _i3.Future<_i8.Size>.value(_FakeSize_10(
          this,
          Invocation.method(
            #getWindowMaxSize,
            [],
          ),
        )),
      ) as _i3.Future<_i8.Size>);
}
