name: colors-ai
version: git
summary: Colors AI
description: A color scheme generator that uses deep learning from public APIs.
source-code: https://github.com/tsinis/colors_ai
confinement: strict
license: MIT
base: core20
grade: stable
compression: lzo
architectures:
  - build-on: [amd64]

parts:
  colors-ai:
    source: .
    plugin: flutter
    build-snaps: [yq]
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - curl
      - gnome-keyring
      - libblkid1
      - libgles2-mesa-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer1.0-dev
      - libgtk-3-dev
      - libjsoncpp-dev
      - liblzma-dev
      - libpcre3-dev
      - libsecret-1-dev
      - ninja-build
      - pkg-config
      - unzip
      - xz-utils
      - zip
    stage-packages:
      - gnome-keyring
      - gstreamer1.0-alsa
      - gstreamer1.0-gl
      - gstreamer1.0-gtk3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-qt5
      - gstreamer1.0-x
      - libjsoncpp-dev
      - libpcre3-dev
      - libsecret-1-0
    override-build: |
      snapcraftctl build
      version=$(yq r pubspec.yaml version | cut -d'+' -f1)
      snapcraftctl set-version "$version"

apps:
  colors-ai:
    command: bin/colors_ai
    extensions: [gnome-3-38]
    plugs:
      - home
      - network