name: colors-ai
version: git
summary: Colors AI
description: A color scheme generator that uses deep learning from public APIs.
source-code: https://github.com/tsinis/colors_ai
confinement: strict
license: MIT
base: core22
grade: stable
compression: lzo
architectures:
  - build-on: [amd64]

parts:
  colors-ai:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libblkid1
      - libjsoncpp-dev
      - libsecret-1-dev
      - cmake
      - curl
      - clang
      - unzip
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgles2-mesa-dev
      - xz-utils
      - zip
    stage-packages:
      - libsecret-1-dev

apps:
  colors-ai:
    command: bin/colors_ai
    extensions: [gnome]
    plugs:
      - home
      - network
