name: colors-ai
version: 2.1.0
summary: Colors AI
description: A color scheme generator that uses deep learning from public APIs.

confinement: strict
license: MIT
base: core20
grade: devel
compression: lzo
architectures:
  - build-on: [amd64]

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: stable
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - libjsoncpp-dev
      - libsecret-1-dev
      - cmake
      - curl
      - clang
      - unzip
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgles2-mesa-dev
      - xz-utils
      - zip
    stage-packages:
      - libjsoncpp1
      - libsecret-1-dev
    override-prime: ""

  build-app:
    after: [flutter-git]
    plugin: nil
    source: .
    stage-packages:
      - libjsoncpp1
      - libsecret-1-dev
    override-build: |
      set -eux
      flutter channel stable
      flutter upgrade
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      flutter gen-l10n
      rm -rf build
      flutter build linux --release -v
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/

apps:
  colors-ai:
    command: bin/colors-ai
    extensions: [gnome-3-38]
    plugs:
      - home
      - network
