name: colors-ai
version: 1.5.0
summary: Colors AI
description: A color scheme generator that uses deep learning from Colormind.
confinement: strict
license: MIT
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]

apps:
  colors-ai:
    command: colors_ai
    extensions: [flutter-beta]
    plugs:
      - network
      - home

parts:
  colors-ai:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-build: |
      flutter pub get
      flutter gen-l10n
      snapcraftctl build
