name: colors-ai
version: 2.1.0
summary: Colors AI
description: A color scheme generator that uses deep learning from public APIs.
confinement: strict
license: MIT
base: core20
grade: devel
architectures:
  - build-on: [amd64]

apps:
  colors-ai:
    command: colors_ai
    extensions: [flutter-stable]
    plugs:
      - home
      - network

parts:
  colors-ai:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libjsoncpp-dev
      - libsecret-1-dev
      - clang cmake
      - ninja-build
      - pkg-config
      - libgtk-3-dev
      - liblzma-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libjsoncpp1
      - libsecret-1-dev
    override-build: |
      flutter pub get
      flutter gen-l10n
      snapcraftctl build
