name: colors-ai
version: 2.0.0
summary: Colors AI
description: A color scheme generator that uses deep learning from public APIs.
confinement: strict
license: MIT
base: core18
grade: stable
architectures:
  - build-on: [ amd64 ]

apps:
  colors-ai:
    command: colors_ai
    extensions: [flutter-stable]
    plugs:
      - home
      - network

parts:
  colors-ai:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - cmake
      - libjsoncpp-dev
      - libsecret-1-dev
      - libvlc-dev
      - vlc
    stage-packages:
      - libjsoncpp1
      - libsecret-1-dev
    override-build: |
      flutter pub get
      flutter gen-l10n
      snapcraftctl build
