name: colors-ai
version: 2.0.0
summary: Colors AI
description: A color scheme generator that uses deep learning from public APIs.
confinement: strict
license: MIT
base: core20
grade: stable
architectures:
  - build-on: [ amd64 ]

apps:
  colors-ai:
    command: colors_ai
    extensions: [flutter-beta]
    plugs:
      - network
      - home

parts:
  colors-ai:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - vlc
      - libvlc-dev
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-dev
      - libjsoncpp1
    override-build: |
      flutter pub get
      flutter gen-l10n
      snapcraftctl build
