name: analyze

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "pubspec.yaml"
      - ".github/workflows/analyze.yaml"

jobs:
  analysis:
    name: 🕵️ Analyze
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    timeout-minutes: 10
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Check spelling
        uses: check-spelling/check-spelling@v0.0.20
        with:
          config: .github/workflows/actions_settings/check-spelling
          check_extra_dictionaries: ""
          extra_dictionaries: cspell:html/html.txt
            cspell:filetypes/filetypes.txt

      - name: Install Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
          channel: 'beta'

      - name: Install app dependencies
        run: flutter pub get

      - name: Analyze project
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-warnings: true
          fatal-infos: true

      - name: Dart Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: "lib, test, integration_test"
          pull_request_comment: true
          check_unused_files: true
          fatal_performance: true
          fatal_warnings: true
          fatal_style: true
