name: analyze

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "pubspec.yaml"
      - ".github/workflows/analyze.yaml"

jobs:
  analysis:
    name: 🔬 PR analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Check spelling
        uses: check-spelling/check-spelling@main
        with:
          config: .github/workflows/actions_settings/check-spelling
          check_extra_dictionaries: ""
          extra_dictionaries: cspell:html/html.txt
            cspell:filetypes/filetypes.txt

      - name: Install Flutter
        uses: subosito/flutter-action@v2.7.1
        with:
          channel: "stable"
          cache: true

      - name: Install app dependencies
        run: flutter pub get

      - name: Analyze project
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true

      - name: Dart Code Metrics
        uses: dart-code-checker/dart-code-metrics-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folders: "lib, test, integration_test"
          pull_request_comment: true
          fatal_warnings: true
          fatal_performance: true
          fatal_style: true
          check_unused_files: true
          check_unused_files_folders: "lib"
