name: analyze

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "pubspec.yaml"
      - ".github/workflows/analyze.yaml"

jobs:
  analysis:
    name: 🕵️ Analyze
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    timeout-minutes: 10
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v4

      - name: Check spelling
        uses: check-spelling/check-spelling@v0.0.21
        with:
          config: .github/workflows/actions_settings/check-spelling
          check_file_names: 1
          only_check_changed_files: 1
          check_extra_dictionaries: ""
          extra_dictionaries:
            cspell:html/html.txt
            cspell:dart/src/dart.txt
            cspell:filetypes/filetypes.txt

      - name: Install Flutter
        uses: subosito/flutter-action@v2.10.0
        with:
          cache: true
          channel: 'stable'

      - name: Install app dependencies
        run: flutter pub get

      - name: Analyze project
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-warnings: true
          fatal-infos: true

      - name: Dart Code Metrics
        run: dart run dart_code_metrics:metrics --disable-sunset-warning --fatal-style --fatal-performance --fatal-warnings --reporter=github lib test integration_test
