name: backup

on:
  push:
    branches:
      - main

jobs:
  mirror-to-gitlab:
    name: 💾 Backup to GitLab
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 📚 Checks-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🪞 Mirroring Repository
        uses: pixta-dev/repository-mirroring-action@v1.1.1
        with:
          target_repo_url: git@gitlab.com:tsinis/colors_ai.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}