name: integration_tests

on:
  pull_request:
    branches:
      - release
    paths:
      - "pubspec.yaml"

jobs:
  integration-test:
    name: 📱 Run Android E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2.7.1
        with:
          cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"

      - name: Install app dependencies
        run: flutter pub get

      - name: Run Android integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          arch: x86_64
          api-level: 29
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          force-avd-creation: false
          script: flutter test integration_test
