name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      uses: subosito/flutter-action@v2
    - name: Install app dependencies
      run: flutter pub get
    - name: Create key for data storage
    - uses: finnp/create-file-action@master
        env:
          FILE_NAME: lib/core/services/data_storage.key.dart
          FILE_DATA: "part of 'data_storage.dart'; const String secureKey = 'key';"
    - name: Generate localization files
      run: flutter gen-l10n
    - name: Test app
      run: flutter test --coverage
    - name: Upload coverage to Codecov
      run: curl -s https://codecov.io/bash
      shell: bash
    - uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage/lcov.info
