name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
    - name: Install Flutter
      uses: subosito/flutter-action@v2
    - name: Install app dependencies
      run: flutter pub get
    - name: Create sample key for data storage
      run: |
        touch ./lib/core/services/data_storage.key.dart
        echo "part of 'data_storage.dart'; const String secureKey = 'key';" >> lib/core/services/data_storage.key.dart
    - name: Generate localization files
      run: flutter gen-l10n
    - name: Test app
      run: flutter test --coverage
    - name: Upload coverage to Codecov
      run: curl -s https://codecov.io/bash
      shell: bash
    - uses: codecov/codecov-action@v2
      with:
        file: ./coverage/lcov.info
