name: microsoft_store_publish

on:
  workflow_dispatch:
  push:
    paths:
      - "lib/**"
      - "assets/**"
      - "pubspec.yaml"
      - "pubspec.lock"
      - "windows/**"
    branches:
      - windows

jobs:
  build-windows:
    runs-on: windows-latest
    name: 🪟 Build Windows app
    timeout-minutes: 15
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2.7.1
        with:
          cache: true

      - name: Enable Windows
        run: flutter config --enable-windows-desktop

      - name: Install Dependencies
        run: flutter packages get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Create MSIX package
        run: flutter pub run msix:create

      - uses: actions/upload-artifact@v3
        with:
          name: windows-release-build
          path: build\windows\runner\Release\colors_ai.msix
          retention-days: 1

  publish-windows:
    needs: build-windows
    runs-on: ubuntu-latest
    name: 🏪 Publish App in Microsoft Store
    steps:
      - uses: actions/download-artifact@v3
        name: Download Release
        with:
          name: windows-release-build
          path: "${{ github.workspace }}/release"

      - uses: isaacrlevin/windows-store-action@1.0
        name: Publish to Store
        with:
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          client-id: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
          app-id: ${{ secrets.WINDOWS_STORE_APP_ID }}
          package-path: "${{ github.workspace }}/release"
