name: tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "pubspec.yaml"
      - ".github/workflows/test.yaml"

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    timeout-minutes: 10
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2.8.0
        with:
          cache: true

      - name: Install app dependencies
        run: flutter pub get

      - name: Test app
        run: flutter test --coverage --no-pub

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 92
          exclude: "**/*.g.dart **/*.gen.dart **/*.freezed.dart"

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          override_branch: ${{ github.base_ref }}
