name: tests

on:
  push:
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "pubspec.yaml"
      - ".github/workflows/test.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "integration_test/**"
      - "pubspec.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2

      - name: Install app dependencies
        run: flutter pub get

      - name: Generate localization files
        run: flutter gen-l10n

      - name: Test app
        run: flutter test --coverage --no-pub

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.1
        with:
          min_coverage: 91
          exclude: "**/*.g.dart **/*.gen.dart **/*.freezed.dart"

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage/lcov.info
